# references:
language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.0

env:
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8
- FRAMEWORK_NAME=SwiftyBase

before_install:
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:

- xcodebuild -workspace Example/SwiftyBase.xcworkspace -scheme "$SCHEME" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;

- xcodebuild -workspace Example/SwiftyBase.xcworkspace -scheme SwiftyBase-Example -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty

- pod lib lint

after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
